// <auto-generated />
namespace Hff.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class deletedMyProperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deletedMyProperty));
        
        string IMigrationMetadata.Id
        {
            get { return "202010301419438_deletedMyProperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
